"""
Unified taxonomy: categories, subcategories, and keyword→tag mapping.

Three-layer system:
1. Source tags → category + subcategory (kulturdaten source_tags)
2. Subcategory keywords → subcategory assignment (DE+EN)
3. Tag keywords → English tags for search/chat enrichment (DE→EN mapping)

Used by all scrapers and the categorizer.
"""

from __future__ import annotations

import re

# ── Source tag → category + subcategory mapping (kulturdaten) ────────────────

SOURCE_TAG_CATEGORY_MAP: dict[str, tuple[str, str | None]] = {
    # Music
    "attraction.category.Concerts": ("music", "live-concert"),
    "attraction.category.Music": ("music", None),
    # Culture
    "attraction.category.Exhibitions": ("culture", "exhibition"),
    "attraction.category.Museums": ("culture", "exhibition"),
    "attraction.category.Theater": ("culture", "theater"),
    "attraction.category.Readings": ("culture", "reading"),
    "attraction.category.Film": ("culture", "cinema"),
    "attraction.category.Dance": ("culture", None),
    "attraction.category.Stages": ("culture", "theater"),
    "attraction.category.Art": ("culture", "gallery"),
    "attraction.category.Lectures": ("meetups", "talk-panel"),
    "attraction.category.Conferences": ("meetups", "talk-panel"),
    # Nightlife
    "attraction.category.Clubs": ("nightlife", "club-night"),
    "attraction.category.Parties": ("nightlife", "party"),
    # Markets
    "attraction.category.Markets": ("markets", None),
    "attraction.category.WeeklyMarkets": ("food", "weekly-market"),
    # Food
    "attraction.category.FoodAndDrink": ("food", None),
    # Workshops
    "attraction.category.Workshops": ("workshops", None),
    # Meetups
    "attraction.category.Community": ("meetups", "community"),
    "attraction.category.Politics": ("meetups", "activism"),
    "attraction.category.InformationEvents": ("meetups", "community"),
    # Outdoors
    "attraction.category.Sports": ("outdoors", "sports"),
    "attraction.category.HealthAndWellness": ("outdoors", "yoga-fitness"),
    "attraction.category.Walks": ("outdoors", "walking-tour"),
    # Family
    "attraction.category.Children": ("family", "kids-program"),
    # Demographic (map to meetups/community as default)
    "attraction.category.Women": ("meetups", "community"),
    "attraction.category.Seniors": ("meetups", "community"),
    "attraction.category.Health": ("meetups", "community"),
    "attraction.category.Education": ("workshops", None),
    # Festivals
    "attraction.category.Festivals": ("culture", "festival"),
    # Skip / exclude
    "attraction.category.Police": (None, None),  # not a real event
    "attraction.category.Recreation": (None, None),  # too generic, use keywords
}

# Legacy compat: old code uses dict[str, str], keep a simple category-only map
SOURCE_TAG_CATEGORY_MAP_SIMPLE: dict[str, str] = {
    k: v[0] for k, v in SOURCE_TAG_CATEGORY_MAP.items() if v[0] is not None
}

# ── Subcategory keywords (DE+EN) ───────────────────────────────────────────
# Used to assign subcategory when source_tag alone isn't specific enough.
# First match wins within a category.

SUBCATEGORY_KEYWORDS: dict[str, dict[str, list[str]]] = {
    "music": {
        "jazz-blues": [
            "jazz",
            "blues",
            "swing",
            "bebop",
            "big band",
            "bigband",
            "soul",
            "funk",
            "r&b",
            "rhythm and blues",
            "blue note",
            "jazzclub",
            "jam session",
        ],
        "electronic": [
            "techno",
            "electronic",
            "electro",
            "synth",
            "ambient",
            "house music",
            "drum and bass",
            "drum & bass",
            "dnb",
            "dubstep",
            "trance",
            "edm",
            "minimal",
            "dj set",
            "dj-set",
            "djset",
        ],
        "classical": [
            "classical",
            "klassik",
            "kammermusik",
            "chamber music",
            "symphony",
            "sinfonie",
            "orchestra",
            "orchester",
            "philharmon",
            "oper",
            "opera",
            "klavier",
            "piano recital",
            "streichquartett",
            "string quartet",
            "cello",
            "violine",
            "sonata",
            "sonate",
            "requiem",
            "kantate",
            "cantata",
            "barock",
            "baroque",
            "orgel",
            "organ recital",
            "chormusik",
            "chor",
            "choir",
            "chorkonzert",
            "akkordeon",
            "accordion",
            "harfe",
            "harp",
        ],
        "rock-pop": [
            "rock",
            "pop",
            "punk",
            "indie",
            "metal",
            "grunge",
            "alternative",
            "garage",
            "post-punk",
            "new wave",
            "singer-songwriter",
            "songwriter",
            "liedermacher",
        ],
        "hip-hop": [
            "hip-hop",
            "hip hop",
            "hiphop",
            "rap",
            "trap",
            "beatbox",
            "freestyle",
            "mc battle",
        ],
        "latin": [
            "latin",
            "salsa",
            "cumbia",
            "reggaeton",
            "bachata",
            "merengue",
            "bossa nova",
            "samba",
            "tango",
            "son cubano",
            "latin jazz",
            "afro-cuban",
            "afrocuban",
            "rumba",
            "mambo",
            "cha-cha",
            "forró",
            "forro",
        ],
        "world-folk": [
            "world music",
            "weltmusik",
            "folk",
            "klezmer",
            "afrobeat",
            "afro",
            "reggae",
            "ska",
            "balkan",
            "flamenco",
            "fado",
            "celtic",
            "irish music",
            "arabic",
            "oriental",
            "indian classical",
            "gamelan",
            "gnawa",
            "ethno",
            "traditional",
            "volksmusik",
        ],
        "live-concert": [
            "konzert",
            "concert",
            "live-musik",
            "live musik",
            "live music",
            "live band",
            "gig",
            "open stage",
            "open mic",
            "unplugged",
            "acoustic",
            "akustik",
            "dozentenkonzert",
            "benefizkonzert",
            "chanson",
        ],
    },
    "nightlife": {
        "club-night": [
            "club night",
            "clubnight",
            "club",
            "rave",
            "afterhour",
            "after hour",
            "berghain",
            "tresor",
            "watergate",
            "about blank",
            "sisyphos",
        ],
        "bar-event": [
            "bar",
            "cocktail",
            "pub",
            "kneipe",
            "happy hour",
            "wine bar",
            "weinbar",
            "taproom",
        ],
        "party": [
            "party",
            "feier",
            "celebration",
            "gala",
            "silvester",
            "new year",
        ],
        "comedy": [
            "comedy",
            "stand-up",
            "standup",
            "stand up",
            "comedian",
            "improv",
            "improvisation",
            "sketch",
            "open mic comedy",
            "kabarett",
            "cabaret",
        ],
        "karaoke": [
            "karaoke",
            "singalong",
            "sing along",
            "sing-along",
        ],
    },
    "culture": {
        "exhibition": [
            "exhibition",
            "ausstellung",
            "exhibit",
            "retrospective",
            "retrospektive",
            "installation",
            "skulptur",
            "sculpture",
            "vernissage",
            "finissage",
            "malerei",
            "painting",
            "gemälde",
            "gemaelde",
            "fotografie",
            "photography",
            "photographie",
            "grafik",
            "graphic art",
            "druckgrafik",
            "plastik",
            "sonderausstellung",
            "dauerausstellung",
            "wanderausstellung",
            "gruppenausstellung",
            "einzelausstellung",
        ],
        "theater": [
            "theater",
            "theatre",
            "schauspiel",
            "bühne",
            "buehne",
            "drama",
            "tragödie",
            "tragoedie",
            "musical",
            "puppentheater",
            "puppet",
            "performance",
            "inszenierung",
            "aufführung",
            "auffuehrung",
            "figurentheater",
            "tanztheater",
        ],
        "cinema": [
            "cinema",
            "kino",
            "film",
            "screening",
            "movie",
            "filmvorführung",
            "filmvorfuehrung",
            "documentary",
            "dokumentarfilm",
            "short film",
            "kurzfilm",
            "filmreihe",
            "filmabend",
        ],
        "reading": [
            "reading",
            "lesung",
            "buchvorstellung",
            "book launch",
            "author",
            "autor",
            "poetry",
            "gedicht",
            "poem",
            "literatur",
            "literature",
            "spoken word",
            "autorenlesung",
            "dichterlesung",
            "lyrik",
            "erzählung",
            "erzaehlung",
            "märchen",
            "maerchen",
        ],
        "gallery": [
            "gallery",
            "galerie",
            "art opening",
            "art show",
            "kunstausstellung",
            "open studio",
            "atelier",
            "offenes atelier",
            "kunstverein",
        ],
        "festival": [
            "festival",
            "kulturfest",
            "biennale",
            "art week",
            "kunstwoche",
            "festspiele",
            "kulturfestival",
        ],
    },
    "food": {
        "brunch": [
            "brunch",
            "frühstück",
            "fruehstueck",
            "breakfast",
            "sunday brunch",
        ],
        "tasting": [
            "tasting",
            "verkostung",
            "wine tasting",
            "beer tasting",
            "weinprobe",
            "degustation",
            "whisky tasting",
        ],
        "pop-up": [
            "pop-up",
            "popup",
            "pop up",
            "supper club",
            "underground dining",
            "secret dinner",
        ],
        "dining-event": [
            "dinner",
            "dining",
            "abendessen",
            "kulinarisch",
            "food event",
            "kitchen",
            "chef",
            "kochen",
        ],
        "food-market": [
            "food market",
            "street food",
            "streetfood",
            "food festival",
            "food truck",
            "markthalle",
        ],
        "weekly-market": [
            "wochenmarkt",
            "weekly market",
            "bauernmarkt",
            "farmers market",
            "farmer",
        ],
    },
    "markets": {
        "flea-market": [
            "flea market",
            "flohmarkt",
            "trödel",
            "troedel",
            "antik",
            "antique",
        ],
        "design-market": [
            "design market",
            "designmarkt",
            "kunstmarkt",
            "art market",
            "handmade",
            "maker market",
        ],
        "pop-up-fashion": [
            "pop-up fashion",
            "fashion market",
            "mode markt",
            "fashion pop-up",
            "vintage fashion",
            "kleidertausch",
        ],
        "secondhand": [
            "second hand",
            "secondhand",
            "vintage",
            "thrift",
            "gebraucht",
            "used clothing",
            "büchertausch",
        ],
        "craft-market": [
            "craft market",
            "kunsthandwerk",
            "handwerkermarkt",
            "artisan market",
            "töpfermarkt",
            "keramikmarkt",
        ],
    },
    "workshops": {
        "creative-workshop": [
            "painting",
            "malen",
            "drawing",
            "zeichnen",
            "pottery",
            "töpfer",
            "toepfer",
            "keramik",
            "ceramic",
            "print",
            "siebdruck",
            "screen print",
            "art workshop",
            "kunstworkshop",
            "kreativ",
            "kreativworkshop",
            "bastel",
            "basteln",
            "gestalten",
            "collagen",
            "collage",
            "kalligraphie",
            "calligraphy",
        ],
        "language": [
            "language",
            "sprach",
            "sprachcafé",
            "sprachcafe",
            "deutsch lernen",
            "german class",
            "deutschkurs",
            "english class",
            "tandem",
            "conversation exchange",
            "sprachkurs",
            "integrationskurs",
        ],
        "digital-skills": [
            "coding",
            "programming",
            "programmier",
            "hackathon",
            "web development",
            "data science",
            "python",
            "javascript",
            "AI workshop",
            "tech workshop",
            "makerspace",
            "maker space",
            "3d druck",
            "3d print",
            "robotik",
            "robotics",
            "lego",
            "digital workshop",
            "digitalworkshop",
        ],
        "dance-class": [
            "dance class",
            "tanzkurs",
            "tanzworkshop",
            "dance workshop",
            "salsa class",
            "tango class",
            "swing class",
            "ballet",
            "ballett",
            "tanztraining",
            "tanzunterricht",
            "tanzen lernen",
            "hip hop kurs",
        ],
        "craft": [
            "craft",
            "handwerk",
            "diy",
            "knitting",
            "stricken",
            "sewing",
            "nähen",
            "naehen",
            "woodwork",
            "holz",
            "upcycling",
            "repair cafe",
            "repair café",
            "repair-café",
            "reparatur",
            "flicken",
            "schmuck",
            "jewelry",
            "töpfern",
        ],
    },
    "meetups": {
        "networking": [
            "networking",
            "meetup",
            "meet-up",
            "mixer",
            "get-together",
            "stammtisch",
            "after-work",
            "afterwork",
            "netzwerk",
        ],
        "community": [
            "community",
            "gemeinschaft",
            "neighborhood",
            "nachbarschaft",
            "kiez",
            "solidarity",
            "solidarität",
            "volunteer",
            "ehrenamt",
            "freiwillig",
            "selbsthilfe",
            "self-help",
            "treff",
            "offener treff",
            "nachbarschaftstreff",
            "beratung",
            "sprechstunde",
        ],
        "tech-startup": [
            "startup",
            "start-up",
            "tech talk",
            "demo day",
            "pitch",
            "founder",
            "gründer",
            "gruender",
            "entrepreneur",
            "innovation",
            "blockchain",
            "web3",
        ],
        "talk-panel": [
            "vortrag",
            "panel",
            "discussion",
            "diskussion",
            "lecture",
            "podium",
            "symposium",
            "conference",
            "konferenz",
            "keynote",
            "presentation",
            "podiumsdiskussion",
            "fachvortrag",
            "infoveranstaltung",
            "gesprächsrunde",
            "gespraechsrunde",
            "buchpräsentation",
        ],
        "activism": [
            "activism",
            "aktivismus",
            "protest",
            "demonstration",
            "political",
            "politisch",
            "climate",
            "klima",
            "social justice",
            "feminism",
            "feminist",
            "gedenken",
            "memorial",
            "solidarisch",
        ],
    },
    "outdoors": {
        "walking-tour": [
            "walking tour",
            "stadtführung",
            "stadtfuehrung",
            "guided tour",
            "city tour",
            "rundgang",
            "neighborhood tour",
            "kieztour",
            "food tour",
            "führung",
            "fuehrung",
            "spaziergang",
        ],
        "sports": [
            "sport",
            "fußball",
            "fussball",
            "football",
            "basketball",
            "volleyball",
            "tennis",
            "badminton",
            "climbing",
            "klettern",
            "bouldern",
            "swimming",
            "schwimmen",
            "tischtennis",
            "ping pong",
            "pingpong",
            "table tennis",
            "hockey",
            "turnen",
            "gymnastics",
            "gymnastik",
            "laufen",
            "running",
            "joggen",
            "jogging",
            "handball",
            "cricket",
            "rugby",
            "baseball",
            "skateboard",
            "skaten",
            "tanzsport",
            "floorball",
            "unihockey",
        ],
        "yoga-fitness": [
            "yoga",
            "fitness",
            "pilates",
            "meditation",
            "qi gong",
            "qigong",
            "tai chi",
            "taichi",
            "workout",
            "stretching",
            "bewegung",
            "körperarbeit",
            "koerperarbeit",
            "achtsamkeit",
            "mindfulness",
            "feldenkrais",
            "ganzkörpergymnastik",
            "gymnastikkurs",
        ],
        "bike-tour": [
            "bike tour",
            "radtour",
            "cycling",
            "fahrrad",
            "bicycle",
            "critical mass",
            "fahrradtour",
        ],
        "outdoor-cinema": [
            "outdoor cinema",
            "open-air kino",
            "open air kino",
            "freiluftkino",
            "sommerkino",
            "outdoor screening",
        ],
    },
    "family": {
        "kids-program": [
            "kids",
            "kinder",
            "children",
            "für kinder",
            "fuer kinder",
            "kindertheater",
            "puppet show",
            "kinderprogramm",
            "kindergarten",
            "bilderbuchkino",
            "kamishibai",
            "vorlesestunde",
            "erzähltheater",
            "erzaehltheater",
            "kindercafé",
            "kindercafe",
            "kinderkino",
            "kinderbibliothek",
            "kinderkonzert",
            "spielenachmittag",
            "kinderworkshop",
        ],
        "family-event": [
            "family",
            "familien",
            "familientag",
            "family day",
            "for all ages",
            "für alle",
            "familiensonntag",
            "familiennachmittag",
            "eltern",
            "parents",
        ],
        "playground": [
            "playground",
            "spielplatz",
            "outdoor play",
            "adventure playground",
            "abenteuerspielplatz",
        ],
        "museum-for-kids": [
            "kindermuseum",
            "kids museum",
            "museum für kinder",
            "science center",
            "labyrinth museum",
            "hands-on",
            "mitmach",
            "mitmachausstellung",
        ],
    },
}

# ── Tag keyword extraction (German→English) ─────────────────────────────────
# FROZEN (unify-taxonomy §1.3): tags are embed-text enrichment only. Do NOT add
# new entries — semantic retrieval via event embeddings has taken over the job
# this vocabulary used to do. No consumer may treat tags as a filtering taxonomy.
# These extract TAGS (not subcategories) from descriptions.
# Tags are always stored in English. Keywords can be German or English.
# A tag can appear regardless of category — it's pure enrichment.

TAG_KEYWORDS: dict[str, list[str]] = {
    "1950s": ["1950er", "50er jahre"],
    "1960s": ["1960er", "60er jahre"],
    "1980s": ["1980er", "80er jahre"],
    "1990s": ["1990er", "90er jahre"],
    "3d-printing": ["3d-druck", "3d-drucken", "3d-drucker"],
    "60s-70s": ["60er jahre", "70er jahre"],
    "80s-90s": ["80er", "90er", "klassiker"],
    "Beatles": ["beatles", "fab four"],
    "DJ": ["dj"],
    "academic-support": ["abitur", "msa", "prüfungen", "schüler:innen"],
    "accessibility": [
        "angepasst",
        "assistenzbedarfe",
        "barrierearm",
        "barrierefreiheit",
        "einfache sprache",
        "erfahrungen teilen",
        "hilfsmittel",
        "lernschwierigkeiten",
        "mobilitätseinschränkungen",
        "niedrigschwellig",
        "ohne voranmeldung",
        "perspektive von betroffenen",
        "rollator",
        "rollstuhl",
        "sicherheit",
        "support",
        "unterstützung",
        "zugang",
        "zugänglichkeit",
    ],
    "accessible": [
        "accessible",
        "affordable",
        "barrierearm",
        "barrierefrei",
        "barrierefreiheit",
        "einfach erklärt",
        "einschränkungen",
        "fortgeschrittene",
        "für anfänger",
        "für jedes nählevel",
        "jedes nählevel",
        "komm vorbei",
        "lernschwierigkeiten",
        "lokal",
        "musikschule",
        "neukölln",
        "offene atmosphäre",
        "rathaus",
        "rollator",
        "rollstuhlgerecht",
        "vorkenntnisse sind nicht erforderlich",
        "wheelchair",
        "zugänglich",
        "zugänglichkeit",
    ],
    "accordion": ["accordion", "akkordeon"],
    "acoustic": ["akustische instrumente", "gitarrenbegleitung", "konzertgitarre"],
    "acrylic-pouring": ["acrylfarben", "acrylic pouring"],
    "administrative": ["dienststelle", "verwaltung"],
    "aerospace": ["luftfahrt", "raumfahrt"],
    "alternative-medicine": [
        "alternative heilmethoden",
        "bach-blüten",
        "heilmethoden",
        "naturheilkunde",
        "natürliche heilmethoden",
    ],
    "alternative-therapy": ["alternative therapie", "komplementärmedizin"],
    "ambient": ["ambient"],
    "android": ["android", "android geräte"],
    "animal-story": ["hasen", "murmeltier", "tiergeschichte"],
    "anniversary": ["25 jahre", "jubiläum"],
    "anti-racism": ["internationalen wochen gegen rassismus", "rassismus"],
    "antisemitism": ["antisemitisch", "antisemitismus"],
    "archaeology": ["archaeologie", "archaeology", "archäologie", "ausgrabung", "grabung"],
    "architecture": [
        "architecture",
        "architektur",
        "bauen",
        "bauhaus",
        "baukunst",
        "festung",
        "friedhof",
        "gotisch",
        "gotisches haus",
        "mittelalterlich",
        "orte",
        "stadtentwicklung",
        "stadträume",
        "städtebau",
        "wohnen",
        "wohnungsmarkt",
        "zitadelle",
    ],
    "art": [
        "aktuelle kunst",
        "ausstellung",
        "ausstellungen",
        "kreativ",
        "kunst",
        "kunstausstellung",
        "künstlergemeinschaft",
        "künstlerisch",
        "künstlerische technik",
        "zak",
    ],
    "art-inspired": ["ausstellung", "künstlerisch"],
    "art-science": ["kunst"],
    "art-workshop": ["kreativ gestalten", "kunst", "workshop"],
    "artificial-intelligence": ["ki", "künstliche intelligenz"],
    "astronomy": ["astronomie", "astronomy", "planetarium", "sterne", "sternwarte"],
    "author": ["author", "autor", "autoren", "autorin", "schriftsteller"],
    "autism": ["ass", "autismus", "autistisches spektrum"],
    "babies": ["0-5 jahre", "babys"],
    "bach-flowers": ["bach-blüten", "bach-blütentherapie", "bachblütentherapie"],
    "bachata": ["bachata"],
    "backup": ["backup", "datensicherung"],
    "balance": ["gleichgewicht", "koordination", "standfestigkeit"],
    "balance-training": [
        "gleichgewicht",
        "gleichgewichtstraining",
        "koordination",
        "standfestigkeit",
    ],
    "baroque": ["barock", "baroque", "pergolesi"],
    "basketball": ["basketball", "streetball"],
    "bebop": ["bebop"],
    "beer": ["beer", "bier", "brauerei", "brewery", "craft beer"],
    "beethoven": ["beethoven"],
    "beginners-welcome": ["jedes nählevel"],
    "berlin": ["berlin"],
    "berlin-artists": ["berlin", "berliner muse"],
    "berlin-community": ["awo berlin", "seniorennetz berlin"],
    "berlin-girls-choir": ["berliner mädchenchor"],
    "berlin-history": [
        "1883-1934",
        "38. ausgabe",
        "bahnhof zoo",
        "berlin",
        "berlin geschichte",
        "berlin wall",
        "berliner mauer",
        "berlins geschichte",
        "charlottenburg",
        "charlottenburg-wilmersdorf",
        "ddr",
        "denkmäler",
        "deutsche geschichte",
        "deutschland",
        "geteilte stadt",
        "hanau",
        "johannisthal",
        "judentum in berlin",
        "mauerweg",
        "nsu",
        "ostpreußendamm",
        "pankow",
        "spandau-geschichte",
        "stadtgeschichte",
        "vergangene zeit",
    ],
    "berlin-humor": ["berlin", "berlinhocker", "brandenburg"],
    "berlin-libraries": ["bibliothek"],
    "berlin-library": ["mittelpunktbibliothek"],
    "berlin-youth": ["berliner mädchenchor", "jugendchor"],
    "bingo": ["bingo", "bingotrommel"],
    "biography": [
        "biografie",
        "biographie",
        "familie",
        "familie niederkirchner",
        "familiengeschichte",
        "familien­geschichte",
        "käte niederkirchner",
        "leben",
        "lebengeschichte",
        "lebensgeschichte",
        "lebenslauf",
        "niederkirchner",
    ],
    "biology": ["biologie", "biology", "natur", "nature"],
    "blues": ["blues"],
    "board-games": [
        "board game",
        "brettspiel",
        "brettspiele",
        "brettspielnachmittag",
        "freizeit",
        "freizeitaktivitäten",
        "gesellschaftsspiel",
        "kartenspiel",
        "kartenspielen",
        "puzzle-begeisterte",
        "puzzle-fans",
        "puzzlespiele",
        "recreation",
        "spiele",
        "spieleabend",
    ],
    "body-awareness": ["bewegung", "körperwahrnehmung"],
    "body-language": ["körpersprache", "nonverbale kommunikation"],
    "body-movement": ["bewegung", "freies tanzen", "körper"],
    "book": ["book", "buch", "buchpräsentation", "buchvorstellung"],
    "book-binding": [
        "buchbinden",
        "buchbinderei",
        "buchbindung",
        "buchkunst",
        "buchreparatur",
        "buchverschönerung",
        "bücher reparieren",
    ],
    "book-club": [
        "besprechung",
        "buchclub",
        "buchklub",
        "bücheraustausch",
        "bücherdiskussion",
        "bücherfrühstück",
        "büchergespräch",
        "lesegruppe",
        "lesekreis",
        "literaturclub",
    ],
    "bossa-nova": ["bossa nova"],
    "brass": ["blechbläser", "horn"],
    "brass-band": ["blasinstrumente", "blasmusik", "concertband"],
    "brass-ensemble": ["blasinstrumente", "bläser"],
    "brazilian-music": ["brasil", "brasileirisch", "brasilianisch"],
    "breathing": ["atemarbeit", "atmung"],
    "cabaret": ["bühnenerlebnis", "entertainment", "glamourtainment"],
    "career": ["arbeitgeber", "berufliche perspektiven"],
    "career-advice": ["berufsberatung", "karriereberatung"],
    "career-counseling": ["berufsberatung", "berufsinformation"],
    "career-guidance": [
        "berufliche orientierung",
        "berufsberatung",
        "berufserkundung",
        "berufsfelder",
        "berufsinformation",
        "berufsorientierung",
        "berufsvorbereitung",
        "bewerbungsprozedere",
        "einstellungsverfahren",
        "karriere",
        "karriereberatung",
        "übergang schule-beruf",
    ],
    "career-information": ["berufsinformation", "karriereberatung"],
    "careers": ["berufsberatung", "karriere"],
    "carl-orff": ["carl orff", "carmina burana"],
    "carmina-burana": ["carmina burana"],
    "casual": ["locker", "ungezwungen"],
    "casual-gathering": ["plaudern", "zwanglos"],
    "cello": ["cello", "violoncello"],
    "chamber-music": ["chamber music", "kammermusik"],
    "chanson": ["chanson"],
    "chemistry": ["chemie", "gase", "sprudelgas"],
    "chess": ["schach", "schachkurs", "schachspiel"],
    "children": [
        "grundschule",
        "kinder",
        "kindesalter",
        "klasse",
        "schüler",
        "schüler:innen",
        "schülerinnen",
    ],
    "children's-choir": ["kinderchor", "singsalasing"],
    "choir": [
        "chants",
        "choir",
        "chor",
        "chorkonzert",
        "chormusik",
        "chöre",
        "ensemble",
        "fachgruppe",
        "frauenchor",
        "gemeinsames singen",
        "gesang",
        "mädchenchor",
    ],
    "choral": ["chorgesang", "chöre", "liedertag"],
    "christian": ["christlich", "ökumenische"],
    "christianity": ["christlich", "passion", "ökumenisch"],
    "christmas": ["weihnachten"],
    "cinema": ["film", "filmvorführung"],
    "circle-singing": ["circle singing", "zyklische melodien"],
    "civic-education": ["einfach erklärt", "politische bildung"],
    "civic-engagement": [
        "demokratische teilhabe",
        "ehrenamt",
        "ehrenamtliche tätigkeit",
        "wahlrecht",
    ],
    "civil-courage": ["zivilcourage", "zivilcourage-training"],
    "classic-american": ["40er jahre", "60er jahre", "amerika", "golden age of jazz"],
    "classical": [
        "blasmusik",
        "blockflöte",
        "classical",
        "fortgeschrittene schülerinnen und schüler",
        "gesangsklasse",
        "kammerorchester",
        "kirchenlied",
        "klassik",
        "klassische musik",
        "klavierklasse",
        "komposition",
        "konzert",
        "musikschule",
        "musizieren",
        "orchester",
        "schüler",
        "sinfonie",
        "sinfoniekonzert",
        "sinfonisch",
        "streicher",
        "streichinstrumente",
        "streichmusik",
    ],
    "clavichord": ["clavichord", "tasteninstrument"],
    "climate": [
        "climate",
        "klima",
        "klimaschutz",
        "nachhaltigkeit",
        "sustainability",
        "umwelt",
        "umweltbewusstsein",
        "umweltschutz",
    ],
    "climbing": ["bouldering", "bouldern", "climbing", "klettern"],
    "coaching": ["coach", "coaching", "mentalcoach"],
    "coding": ["coding", "programmieren", "programming", "software"],
    "coffee": ["cafe", "café", "coffee", "frühstück", "kaffee", "tee"],
    "cognitive-skills": ["geist aktiv", "mentales training"],
    "collage": ["collage", "collagen", "collagen-workshop"],
    "comedy": [
        "comedygedichtschreiber",
        "helga show",
        "humor",
        "kabarett",
        "kabarettist",
        "kabarettistin",
        "komödie",
        "show",
    ],
    "comics": ["comics", "comiczeichnerinnen"],
    "communication": [
        "gesprächstechniken",
        "klare kommunikation",
        "kommunikation",
        "kommunikationstechniken",
        "kommunikationswissenschaft",
    ],
    "communication-skills": ["diskussionsfähigkeit", "kommunikation", "rhetorik"],
    "community-center": ["stadtteilzentrum"],
    "community-event": [
        "begegnungsstätte",
        "fröhliche gäste",
        "geselliger nachmittag",
        "kommunal",
        "kommunale",
        "kommunale veranstaltung",
    ],
    "community-gathering": ["nachbarschafts-café", "nachbarschaftscafé", "nachbarschaftstreffen"],
    "community-music": ["community music", "gemeinsames singen"],
    "community-safety": ["sicherheit", "öffentliche ordnung"],
    "community-service": [
        "bürgerbeteiligung",
        "bürgerdienst",
        "mobile wache",
        "polizei",
        "öffentlicher dienst",
    ],
    "community-support": [
        "community",
        "digital-lots:innen",
        "gemeinschaftshilfe",
        "gemeinschaftsunterstützung",
        "nachbarschaftshilfe",
        "nachbarschaftsunterstützung",
        "service",
        "servicezeiten",
        "unterstützen",
        "unterstützung",
    ],
    "competition": [
        "ausscheid",
        "european money quiz",
        "finale",
        "preisträger",
        "quiz",
        "wettbewerb",
        "wettkampf",
    ],
    "competitive": ["final", "finale", "landesfinale"],
    "concert": ["abschlusskonzert", "konzert", "serenade", "sommerkonzert"],
    "confidence-building": ["selbstsicherheit", "selbstvertrauen"],
    "conflict-resolution": [
        "deeskalation",
        "fairen streiten",
        "gewaltfreie intervention",
        "konfliktbewältigung",
        "konflikte",
        "konflikten umgehen",
        "konfliktlösung",
        "konfliktmanagement",
    ],
    "contemporary-art": ["contemporary art", "modern art", "moderne kunst", "zeitgenössisch"],
    "contemporary-classical": ["experimentell", "neue musik"],
    "contemporary-fiction": [
        "auster",
        "mcewan",
        "melandri",
        "moderner roman",
        "zeitgenössische literatur",
    ],
    "contemporary-techniques": ["moderne spielpraktiken", "zeitgenössische techniken"],
    "conversation-practice": ["gesprächspraxis", "konversation"],
    "cooking": [
        "acker",
        "backen",
        "baking",
        "cooking",
        "gemüse",
        "kochen",
        "kochkurs",
        "lebensmittel verarbeiten",
        "lehrküche",
        "teller",
        "verpflegung",
    ],
    "coordination": ["koordination"],
    "counseling": [
        "begleitung",
        "beratung",
        "coaching",
        "counseling",
        "digital-lot:innen",
        "digital-lots:innen",
        "gesprächspartnerin",
        "hilfe",
        "impulse",
        "informationsveranstaltung",
        "lot:innen",
        "lots:innen",
        "lotsen",
        "psychologische beratung",
        "selbstfürsorge",
        "servicezeiten",
        "sozialpädagoge",
        "sprechstunde",
        "support",
        "systemische beratung",
        "training",
        "unterstützen",
        "unterstützung",
    ],
    "country": ["country", "country-musik"],
    "country-dance": ["country-linedance", "linedance"],
    "cover-band": ["cover-band", "coverband", "tribute"],
    "crafting": [
        "basteln",
        "bastelwerkstatt",
        "diy",
        "gestalten",
        "handwerk",
        "kreativ",
        "kreative runde",
    ],
    "crafts": ["ausprobieren", "basteln", "diy", "gestaltet", "handwerk", "kreativ", "kunstwerke"],
    "creative": [
        "fantasie",
        "kreativ",
        "kreativ werkstatt",
        "kreative",
        "kreative köpfe",
        "kreative werkstatt",
        "kreatives abenteuer",
        "kreativität",
        "kreativwerkstatt",
        "kunsthandwerk",
        "künstlergemeinschaft",
    ],
    "creative-activities": ["kreative aktivitäten", "kreative aktivtäten"],
    "creative-community": ["kreativ", "kreative runde"],
    "creative-crafts": ["kreativität", "techniken"],
    "creative-expression": [
        "fantasie",
        "kreativ",
        "kreative gestaltung",
        "kreativität",
        "künstlerisch",
        "künstlerische entfaltung",
    ],
    "creative-play": [
        "ausprobiert",
        "fantasie",
        "ideenwerkstatt",
        "kreativ",
        "kreativ werkstatt",
        "kreative",
        "kreatives abenteuer",
        "kreatives spiel",
        "kreatives spielen",
        "kreativwerkstatt",
        "spielerisch",
    ],
    "creative-workshop": [
        "basteln",
        "gestalten",
        "ideenwerkstatt",
        "inspiration",
        "inspirieren",
        "kreativ",
        "kreativ werkstatt",
        "kreative aktivitäten",
        "kreative runde",
        "kreative workshop",
        "kreativität",
        "kreativwerkstatt",
        "kurs",
        "workshop",
    ],
    "creative-writing": [
        "kreatives schreiben",
        "schreibcafé",
        "schreiben",
        "schreibimpulse",
        "schreibwerkstatt",
    ],
    "creativity": ["fantasie", "kreativ", "künstlerisch", "schreibimpulse"],
    "crime-prevention": ["kriminalprävention"],
    "critical-thinking": ["fehlannahmen", "missverständnisse", "mythen"],
    "crochet": ["häkel", "häkelprojekt"],
    "culture": ["kultur", "kultureller reichtum"],
    "cumbia": ["cumbia"],
    "cybersecurity": ["datenschutz", "datensicherheit", "gerätesicherheit", "sicherheit"],
    "cycling": ["cycling", "fahrrad", "radfahren", "radtour", "zweiräder"],
    "dance": [
        "dance",
        "dancing",
        "getanzt",
        "linedance",
        "mitmachtänze",
        "schwofen",
        "tanz",
        "tanzangebot",
        "tanzcafé",
        "tanzen",
        "tanzfläche",
        "tanzklasse",
        "tanzkreis",
        "tanzkurs",
        "tanznachmittag",
        "tanzstunde",
        "tanzunterricht",
        "tanzveranstaltung",
        "tanzzeit",
        "volkstanz",
    ],
    "dance-therapy": [
        "dansevita",
        "tanztherapeutisch",
        "tanztherapeutischen methode",
        "tanztherapie",
    ],
    "data-management": ["datenverwaltung", "digitale daten", "speichern"],
    "dating": ["dating", "flirten"],
    "ddr-history": [
        "ddr-geschichte",
        "east germany",
        "ostalgie",
        "ostdeutschland",
        "traditionsbildung",
    ],
    "debussy": ["debussy"],
    "decluttering": ["ausmisten", "entrümpeln", "konmari", "loslassen"],
    "decoration": ["farbschnitte", "strasssteine", "verschönerung", "verzieren", "verzierung"],
    "dementia-friendly": ["demenz", "demenzfreundlich"],
    "democracy": [
        "democracy",
        "demokratie",
        "demokratische institutionen",
        "demokratische kultur",
        "demokratische ordnung",
        "demokratische teilhabe",
        "grundgesetz",
        "verfassung",
        "wahlen",
    ],
    "design": ["aufkleber-design", "design", "kartengestaltung", "kunst"],
    "digital-media": ["digitale medien"],
    "disability-rights": ["barrierefreiheit", "behinderung", "menschen mit behinderungen"],
    "discrimination-awareness": ["diskriminierung ost", "sensibilisierung"],
    "discussion": [
        "austausch",
        "diskussion",
        "diskussionsreihe",
        "diskutiert",
        "gespräch",
        "gesprächsreihe",
    ],
    "diy": [
        "ausprobieren",
        "diy",
        "geräte nutzen",
        "selber machen",
        "selbermachen",
        "selbst gemacht",
    ],
    "dj-set": ["dj"],
    "documentary": ["dokumentarfilm", "dokumentarisch", "dokumentation"],
    "documentary-style": ["arbeitermilieu", "politischen film"],
    "drop-in": [
        "keine anmeldung erforderlich",
        "offene werkstatt",
        "offenes angebot",
        "offenes zusammenkommen",
        "ohne anmeldung",
    ],
    "dual-study": ["duales studium"],
    "e-bikes": ["e-bikes", "e-mobilität", "pedelecs"],
    "e-mobility": ["e-bikes", "e-mobilität", "e-scooter", "pedelecs"],
    "e-reader": ["e-reader", "tolino", "tolino e reader"],
    "e-readers": ["tolino e reader"],
    "east-germany": ["ostdeutschland"],
    "easter": ["osterhasen", "osterkerzen", "ostern"],
    "easter-holiday": ["osterferien", "schulferien"],
    "educational": ["bildung", "vorführung"],
    "elderly-friendly": ["hilfe mit smartphone", "internet-probleme"],
    "electronic": ["electro", "electronic", "elektronisch"],
    "elementary-school": ["1. & 2. klasse", "1. klasse", "2. klasse", "grundschule"],
    "embroidery": ["motive", "muster", "sticken", "stickmaschine"],
    "emotional": ["emotional", "gefühlvoll"],
    "empathy": ["empathie", "menschlichkeit"],
    "english-friendly": [
        "a2/b1",
        "auf englisch",
        "barrierefrei zugänglich",
        "englisch",
        "englisch a2/b1",
        "englischsprachig",
        "english",
        "english-speaking",
        "in english",
        "mehrsprachig",
        "neuköllner bibliotheken",
        "odihr",
        "osze",
    ],
    "english-language": [
        "englisch",
        "englisch a2/b1",
        "englischkurs",
        "english",
        "english conversation",
    ],
    "ensemble": [
        "ensemble",
        "ensembles",
        "ensembleunterricht",
        "gemeinschaftskonzert",
        "orchester",
    ],
    "ensemble-playing": ["duos", "ensemble"],
    "erasmus": ["erasmus+", "erasmus-förderung"],
    "erasmus-plus": ["erasmus+", "europäischer austausch"],
    "ethics": ["ethik", "ethische fragen"],
    "europe": ["eu", "europa", "europäisch", "europäische union"],
    "european-collaboration": ["europäische projektarbeit", "internationaler austausch"],
    "european-culture": ["europa", "europäisch"],
    "exam-prep": ["abi", "abitur", "msa", "prüfungen", "prüfungsvorbereitung"],
    "exam-preparation": ["abi", "abitur", "msa", "prüfungsvorbereitung"],
    "experimental": ["experimentelle erkundungen"],
    "fairy-tales": ["fabel", "fairy tale", "hase und igel", "maerchen", "märchen"],
    "fall-prevention": [
        "sicherheit",
        "sturzprophylaxe",
        "sturzprävention",
        "stürze",
        "stürze verhindern",
        "stürze vermeiden",
    ],
    "family-friendly": [
        "ab 6 jahren",
        "eltern",
        "familienfreundlich",
        "family-friendly",
        "freizeitstätte",
        "für alle altersgruppen",
        "für jedes nählevel",
        "gemeinsam",
        "heitere seite",
        "jugend",
        "kinder",
        "konzert",
        "lebenslange fans",
        "musikschule",
        "mädchen",
        "nachbarschafts- und familienzentrum",
        "nachbarschaftszentrum",
        "rathaus",
        "schüler",
        "schüler:innenvorspiel",
        "studierende",
        "u18",
        "vorspiel",
    ],
    "family-history": [
        "familie",
        "familie niederkirchner",
        "familienerbe",
        "familiengedächtnis",
        "familiengeschichte",
        "familiennachlass",
        "familienvergangenheit",
        "familiärem",
        "familiärem erinnern",
    ],
    "farm-to-table": ["vom acker auf den teller"],
    "fashion": ["haute couture", "jeans", "kleidung", "mode", "modedesignerin"],
    "female": ["frauenlauf", "mädchenlauf"],
    "festival": [
        "ausgabe",
        "fest",
        "international",
        "internationale",
        "internationale veranstaltung",
        "jährlich",
        "straßenfest",
        "workshop",
    ],
    "fiction": ["belletristik"],
    "film-history": ["filmgeschichte", "filmwissenschaft"],
    "film-music": ["filmmusik", "how to train your dragon"],
    "finance": [
        "anlageberatung",
        "economy",
        "finance",
        "finanzbildung",
        "finanzen",
        "finanzwissen",
        "geld",
        "geldwissen",
        "investieren",
        "money",
        "wirtschaft",
    ],
    "fitness": [
        "bewegung",
        "fitness",
        "gleichgewichtstraining",
        "koordination",
        "kraft",
        "training",
        "übungen",
    ],
    "flamenco": ["flamenco"],
    "flute": ["flöte", "querflöte"],
    "folk": ["folk", "liedgut", "volkslieder", "volksmusik"],
    "folk-culture": ["folklore", "folkloreträchtig"],
    "folk-dance": [
        "europäische tänze",
        "gesellige tänze",
        "mitmachtänze",
        "volkstanz",
        "volkstänze",
    ],
    "folk-music": ["kinderlieder", "volkslied", "volkslieder"],
    "folk-songs": ["kinderlieder", "volkslieder"],
    "food": ["essen", "kulinarische köstlichkeiten", "lebensmittel", "verpflegung"],
    "food-science": ["ernährung", "lebensmitteltechnik"],
    "football": ["football", "fussball", "fußball", "soccer"],
    "fortress": ["festung", "zitadelle"],
    "freddie-mercury": ["freddie mercury"],
    "free": [
        "angebot",
        "anmeldung",
        "eintritt frei",
        "eintritt ist frei",
        "entgeltfrei",
        "free",
        "free admission",
        "free entry",
        "frei",
        "freies angebot",
        "gratis",
        "keine anmeldung",
        "keine gebühr angegeben",
        "keine preisangabe",
        "kosten: keine",
        "kostenfrei",
        "kostenfrei im februar",
        "kostengünstig",
        "kostenlos",
        "kostenloses angebot",
        "kostenpflichtig",
        "ohne anmeldung",
        "spende",
        "umsonst",
        "vhs",
    ],
    "free-or-cheap": ["2€", "preiswert"],
    "functional-movement": ["alltag", "aufstehen", "bewegung", "hinsetzen"],
    "funk": ["funk"],
    "gaming": [
        "ausprobieren",
        "bingo",
        "bingo-spiel",
        "computerspiel",
        "computerspiele",
        "game",
        "gaming",
        "glücksrad",
        "spiel",
        "spiele",
        "spiele-ag",
        "spielen",
        "spieler",
        "spieltermine",
        "videospiele",
    ],
    "genesis": ["genesis"],
    "geography": ["geografie", "land", "länderreise"],
    "german-history": ["deutsche geschichte"],
    "german-language": [
        "auf deutsch",
        "berlin",
        "bibliotheken",
        "deutsch",
        "deutsch lernen",
        "deutsche beratung",
        "deutsche lieder",
        "deutsche sprache",
        "deutschen liedern",
        "deutschkurs",
        "deutschsprachig",
        "deutschunterricht",
        "englisch",
        "german class",
        "grammatik",
        "integration",
        "lesen",
        "lesenlernen",
        "nachhilfe",
        "neukölln",
        "neuköllner bibliotheken",
        "sprache",
        "sprachenlernen",
        "sprachkurs",
    ],
    "german-literature": [
        "deutsche literatur",
        "deutschsprachige literatur",
        "martin suter",
        "rilke",
        "ringelnatz",
    ],
    "german-new-wave": ["ndw", "neue deutsche welle"],
    "german-rock": ["deutsche band", "deutsche rockmusik", "deutschrock", "deutschsprachig"],
    "germany": ["dresden", "thüringen", "vogtland"],
    "governance": ["ehrenamtlich", "verwaltungsamt"],
    "grammar": ["grammatik", "grammatikübungen", "zeiten"],
    "graphic-art": ["druckgrafik", "grafik", "graphic art", "holzschnitt", "lithografie"],
    "group-activity": ["gemeinsam", "gemeinsames singen", "gruppe", "kollektiv"],
    "group-music": ["spielkreis", "zusammen spielen", "zusammen ukulele spielen"],
    "group-playing": ["spielkreis", "zusammen spielen"],
    "group-singing": ["chants", "gemeinsames singen"],
    "guided-tour": [
        "führung",
        "führungen",
        "kidsführung",
        "kidsführungen",
        "stadtrundgang",
        "tastführung",
    ],
    "guitar": ["gitarre", "gitarrenklasse", "gitarrenkurs", "guitar", "zupfinstrumente"],
    "gymnastics": ["gymnastics", "gymnastik", "turnen"],
    "handcraft": ["handarbeit", "handwerk"],
    "hands-on": [
        "anleitung",
        "ausprobieren",
        "mit den eigenen händen",
        "praktisch",
        "unter anleitung",
        "zum anfassen",
    ],
    "hands-on-learning": ["experimente", "praktisches lernen"],
    "health": [
        "bewegung",
        "ergotherapeutin",
        "gesundheit",
        "mobilität",
        "sicherheit",
        "therapeutisch",
    ],
    "health-wellness": ["alltag", "gesundheit", "prävention", "sicherheit", "wohlbefinden"],
    "herbal-medicine": ["botanisch", "pflanzenheilkunde"],
    "hip-hop": ["hip hop", "hip-hop", "hiphop"],
    "history": [
        "40er - 60er jahre",
        "amerika",
        "berlin-mitte",
        "ddr-geschichte",
        "erbe",
        "erinnern",
        "festungsgeschichte",
        "geschichte",
        "historical",
        "historiker",
        "historisch",
        "historische",
        "historische brüche",
        "history",
        "hoboken",
        "hollywood",
        "kontinuität",
        "las vegas",
        "längst vergangene zeit",
        "new york",
        "ostdeutsche geschichte",
        "vergangene zeit",
        "vergangenheit",
        "zeitgeschichte",
    ],
    "hobby": ["freizeitaktivität", "hobby"],
    "hockey": ["eishockey", "floorball", "hockey", "schulhockey", "unihockey"],
    "homelessness": [
        "obdach",
        "obdachlos",
        "obdachlose",
        "obdachlosigkeit",
        "wohnungslose",
        "wohnungslosigkeit",
    ],
    "homework-help": ["fragen stellen", "lernhilfe", "lernstudio", "prüfungshilfe"],
    "house": ["house"],
    "housing": ["wohnen", "wohnungslosigkeit", "wohnungsmarkt", "wohnungspolitik"],
    "housing-rights": ["recht auf wohnen", "wohnungsrecht"],
    "human-rights": [
        "grundfreiheiten",
        "menschenrecht",
        "menschenrechte",
        "recht auf wohnen",
        "rechtsstaatlichkeit",
        "wohnungslosigkeit",
    ],
    "humor": ["witz", "witzig"],
    "illusion": ["illusionen", "tricks"],
    "illustration": ["comic", "farben", "graphic novel", "illustration", "manga", "strich"],
    "improv-theater": ["improtheater", "improvisationstheater"],
    "improvisation": ["improvisation", "improvisiert", "improvisionationen"],
    "inclusive": [
        "barrierefreiheit",
        "diversity",
        "einzeln",
        "erfahrene spieler",
        "erfahrene spieler/-innen",
        "fortgeschrittene",
        "gegenseitige achtung",
        "gemeinschaft",
        "inclusive",
        "inklusion",
        "inklusiv",
        "interessierte",
        "jedes nählevel",
        "keine vorkenntnisse",
        "lernschwierigkeiten",
        "neue spieler:innen sind willkommen",
        "offenes zusammenkommen",
        "offenheit",
        "singerfahrungen nicht erforderlich",
        "spezielle bedürfnisse",
        "willkommen",
        "zu zweien",
        "zugänglich",
    ],
    "indie": ["indie"],
    "indie-pop": ["alternative", "indie-pop"],
    "indigenous-peoples": ["indigene völker"],
    "indoor": ["bibliothek", "drinnen"],
    "information-session": ["berufsinformation"],
    "inheritance": ["erbe", "nachlass"],
    "installation": ["installation", "rauminstallation", "soundinstallation"],
    "instrument-exploration": ["instrumentenkunde", "wie ist eine orgel aufgebaut"],
    "instrument-rental": ["ausleihe", "leihgebühr"],
    "instrument-workshop": ["alle instrumente", "werkstatt"],
    "instrumental": ["grundlagen", "instrumental", "instrumentalunterricht"],
    "instrumental-training": ["instrumentale grundlagen", "instrumentalunterricht"],
    "instruments": ["instrumente", "schlagzeug", "trompete", "xylophon"],
    "intensive-course": ["intensiv", "workshop"],
    "intensive-training": ["ensemble-unterricht", "intensiver unterricht"],
    "interactive-learning": ["interaktiv", "spielerisch", "tastführung"],
    "intergenerational": [
        "erwachsene",
        "erwachsenen",
        "generationenübergreifend",
        "jugendliche",
        "jugendliche und erwachsene",
        "unterschiedlicher generationen",
        "zusammenarbeit",
    ],
    "intermediate": ["intermediate", "intermediate course", "mittelstufe"],
    "intermediate-level": ["intermediate", "intermediate course", "mittelstufe"],
    "international": ["international", "internationaler"],
    "international-relations": ["ausland", "internationale beziehungen", "osze", "warschau"],
    "internet": ["internet", "online", "smartphone"],
    "internet-support": ["internet", "internet-unterstützung", "internetprobleme", "online-hilfe"],
    "intimate": ["besonderer musikalischer nachmittag", "hautnah"],
    "investing": ["aktien", "etfs", "investieren", "wertpapiere"],
    "jazz": ["jazz", "jazzworkshop", "swingin'"],
    "jazz-blues": ["frank sinatra"],
    "jewelry-making": ["schmuckanhänger", "schmuckherstellung"],
    "job-fair": ["jobmesse"],
    "kamishibai": ["erzähltheater", "kamishibai"],
    "kids": ["1. klasse", "2. klasse", "grundschule", "kinder"],
    "kids-program": [
        "1. & 2. klasse",
        "1. klasse",
        "1. und 2. klasse",
        "2. klasse",
        "für kinder",
        "grundschule",
        "kinder",
        "kinder von 4 bis 12 jahren",
        "kinderbetreuung",
        "kindercafé",
        "kinderprogramm",
        "kinderveranstaltung",
    ],
    "klezmer": ["klezmer"],
    "knitting": ["crochet", "haekeln", "häkeln", "knitting", "strick", "stricken", "stricktreff"],
    "knowledge": ["wissen"],
    "language-exchange": [
        "austausch",
        "conversation",
        "diskussion",
        "gespräch",
        "konversation",
        "language exchange",
        "literaturkreis",
        "lotsen",
        "portugiesisch",
        "sprachaustausch",
        "sprachcafe",
        "sprachcafé",
        "sprache",
        "sprachkurs",
        "sprachtandem",
        "support",
        "tandem",
    ],
    "language-learning": ["sprachenlernen", "sprachenunterricht", "sprachkurs"],
    "language-play": ["sprachspiele"],
    "laser-cutting": [
        "laser",
        "laser-schneiden",
        "laserbearbeitung",
        "lasercut",
        "lasercutter",
        "laserschneiden",
    ],
    "law": ["gericht", "gerichtsverfahren", "jura", "rechtsamt", "richter", "richteramt"],
    "leadership": ["führung", "klassensprecher"],
    "learning-support": ["lernhilfe", "texterfassung"],
    "legal": ["rechtliche aspekte", "rechtsfragen"],
    "lego": ["lego"],
    "library": [
        "ausleihe",
        "bezirkszentralbibliothek",
        "bibliothek",
        "bücherei",
        "medien",
        "medienbestand",
        "stadtteilbibliothek",
    ],
    "library-services": ["bibliothek", "selbstverbucherautomaten"],
    "library-tour": ["bibliothekseinführung", "bibliotheksführung"],
    "lieder": ["lied", "liederabend"],
    "life-skills": ["alltag", "lebenskompetenzen", "praktische strategien"],
    "lifestyle": ["alltag", "interior", "lebensstil", "wohnen", "zuhause"],
    "line-dance": ["line dance", "linedance"],
    "line-dancing": ["country-linedance", "line dance", "line-dance", "linedance", "linedancing"],
    "liszt": ["liszt"],
    "literacy": ["leseförderung", "lesekompetenz", "lesenlernen"],
    "literature": [
        "buchklub",
        "bücher",
        "ficção",
        "fiktion",
        "lieblingsbücher",
        "literarisch",
        "literatur",
        "literaturclub",
        "literature",
        "literaturkreis",
        "novel",
        "rainer maria rilke",
        "roman",
    ],
    "live-band": ["alex band", "band", "live", "live band", "live-band"],
    "live-concert": [
        "aufführung",
        "auftritt",
        "bühnenjubiläum",
        "bühnenshow",
        "concert",
        "frühlingskonzert",
        "jubiläumskonzert",
        "konzert",
        "live",
        "live-auftritt",
        "live-konzert",
        "live-musik",
        "musik",
        "musizieren",
        "soirée",
        "sommerkonzert",
        "turmmusik",
        "vorspiel",
    ],
    "live-music": [
        "klaviermusik",
        "live-musik",
        "livemusik",
        "mit kiry",
        "musik",
        "spielt auf",
        "wolfram schäfer",
    ],
    "live-performance": ["live-vorführung", "musik-show"],
    "logic": ["logisches denken"],
    "love-songs": ["gefühle", "liebe", "romantisch"],
    "magic-show": ["magic show", "magie", "zauberkunst"],
    "makerspace": ["maker", "maker-space", "makerspace", "makerspaces", "reup studios"],
    "mantra": ["chants", "indische mantren", "mantren"],
    "mantras": ["indische mantren", "mantren"],
    "martial-arts": ["aikido", "judo", "kampfsport", "karate", "kung fu", "martial arts"],
    "masterclass": ["meisterkurs", "meisterkurse"],
    "math": ["mathe", "mathematik"],
    "mathematics": ["mathe", "mathematik"],
    "mechanical-instruments": [
        "drehorgel",
        "leierkasten",
        "mechanische instrumente",
        "mechanische musikinstrumente",
        "orchestrion",
        "spielklavier",
    ],
    "mechanical-music": [
        "drehorgel",
        "mechanische musikinstrumente",
        "musica di strada",
        "orchestrion",
        "spielklavier",
    ],
    "media-education": ["medienpädagogik"],
    "media-technology": ["mediengestaltung", "medientechnologie"],
    "mediation": ["mediation", "mediatorin"],
    "medieval": ["gotisches haus", "mittelalterlich"],
    "medieval-history": ["konzil", "mittelalter"],
    "meditation": ["chants", "indische", "mantren", "meditation", "meditativ"],
    "melancholic": ["melancholie", "sehnsucht"],
    "memorial": [
        "19. februar hanau",
        "denkmal",
        "erinnern",
        "erinnerung",
        "gedenkstätte",
        "gedenktafel",
        "opfer",
    ],
    "memorial-culture": ["erinnerung", "erinnerungskultur", "gedenken", "gedenkkultur"],
    "memory": ["erinnerung", "gedenken"],
    "memory-culture": [
        "erinnern",
        "erinnerung",
        "erinnerungskultur",
        "gedenken",
        "gedenkkultur",
        "gedenkstätte",
        "gedächtnis",
        "verdrängen",
    ],
    "memory-studies": ["erinnern", "gedenken", "verdrängen"],
    "mentalism": ["gedankenlesen", "mentalmagie"],
    "metal": ["metal"],
    "metalworking": ["metallbearbeitung", "metallwerkstatt"],
    "middle-ages": ["konzil", "mittelalter"],
    "migration": [
        "asyl",
        "asylverfahren",
        "diaspora",
        "einwanderung",
        "erbe",
        "erinnerungskultur",
        "exil",
        "familie",
        "familiengeschichte",
        "flucht",
        "geflüchtete",
        "migrant*innen",
        "migration",
        "migrationserfahrung",
        "türkischstämmig",
    ],
    "mindfulness": [
        "achtsamkeit",
        "atemtiefe",
        "atmung",
        "beruhigt",
        "bewegt die seele",
        "bewusst",
        "entspannt",
        "entspannung",
        "fantasiereisen",
        "geist",
        "innere ruhe",
        "inspiriert den geist",
        "lebendigkeit",
        "leichtigkeit",
        "meditativ",
        "persönliche weise",
        "seele",
    ],
    "minimalism": ["entkluttering", "konmari", "leichtigkeit", "minimalismus"],
    "mobile": ["fabi", "lastenfahrrad"],
    "mobile-program": ["lastenfahrrad", "unterwegs"],
    "monument-culture": ["gedenken", "instrumentalisierung", "legendenbildung"],
    "motorcycles": ["krafträder", "zweiräder"],
    "movement": ["bewegung", "körper", "lebendigkeit", "sich zur musik bewegen"],
    "movement-meditation": ["fantasiereisen"],
    "movement-therapy": ["körper", "lebendigkeit", "seele"],
    "movement-wellness": ["körper", "lebensfreude", "seele"],
    "multilingual": ["mehrsprachig"],
    "multimedia": ["multimediashow", "überblendtechnik"],
    "multimedia-show": ["bild- und musikromanzen", "multimediashow"],
    "multisensory": ["multisensorisch", "sensorisch", "sinne", "sinneserfahrung"],
    "museum": ["ausstellung", "dauerausstellung", "gotisches haus", "museum", "zak", "zitadelle"],
    "museum-for-kids": ["kinder", "museumsführung", "schulklassen"],
    "museum-tour": ["ausstellung", "führung"],
    "museum-visit": ["ausstellung", "museum", "zitadelle"],
    "music": [
        "bühnenprogramm",
        "ensemble",
        "gesangseinlagen",
        "instrumental",
        "instrumentalunterricht",
        "instrumente",
        "konzert",
        "lied",
        "lieder",
        "mukiba",
        "musik",
        "musikalisch",
        "musikalische einlagen",
        "musikgenuss",
        "musikinstrumente",
        "musikschule",
        "musikunterricht",
        "musizieren",
        "vorspiel",
    ],
    "music-education": ["musikpädagogik", "musikschule", "musikunterricht", "orgelkurs"],
    "music-history": ["mechanische musikinstrumente", "musikgeschichte"],
    "music-school": ["musikschule"],
    "music-theater": ["musiktheater"],
    "musical": ["musical", "musicalaufführung"],
    "musical-instruments": ["instrumente", "instrumentenunterricht", "trompete", "xylophon"],
    "natural-medicine": ["naturheilkunde", "natürliche heilmethoden"],
    "nature": [
        "botanisch",
        "exkursionen",
        "gletscher",
        "landschaft",
        "umgebung",
        "vulkane",
        "wüste",
    ],
    "networking": [
        "austausch",
        "erfahrungenaustausch",
        "erfahrungsaustausch",
        "kontakte knüpfen",
        "partnerfindung",
        "partnersuche",
        "vernetzung",
    ],
    "no-registration": ["freier zugang", "ohne anmeldung"],
    "nostalgia": ["einmalige zeit", "hits", "vergangene zeit", "vergangenheit"],
    "nutrition-education": ["ernährung", "ernährungsbildung"],
    "oboe": ["oboe"],
    "online": [
        "buchklub",
        "kurs",
        "link",
        "online",
        "online statt",
        "online-seminar",
        "teilnahme-link",
        "virtuel",
        "virtuelle teilnahme",
    ],
    "online-safety": ["digitale sicherheit", "hassan­griffe", "schutz im netz"],
    "open-access": ["für alle", "offen", "offenes zusammenkommen", "ohne anmeldung"],
    "open-day": ["informationstag", "tag der offenen tür"],
    "open-drop-in": ["offenes zusammenkommen", "ohne anmeldung"],
    "open-format": ["offenes zusammenkommen", "ohne anmeldung"],
    "open-house": ["tag der offenen tür"],
    "open-studio": ["offen", "offene werkstatt", "offenes zusammenkommen", "ohne anmeldung"],
    "open-to-all": ["alle", "für alle", "offen", "offenes zusammenkommen", "ohne anmeldung"],
    "opera": ["oper", "opera"],
    "orchestra": [
        "concertband",
        "jugendorchester",
        "jugendstreichorchester",
        "kinderstreichorchester",
        "musikschule",
        "orchester",
        "orchesterschule",
        "sinfonietta",
        "streichensemble",
        "streicher",
    ],
    "organ": ["organ", "orgel"],
    "organization": ["aufräumen", "ausmisten", "ordnung", "organisieren"],
    "outdoor": [
        "ackerflächen",
        "an der zitadelle",
        "draussen",
        "draußen",
        "exkursionen",
        "freigelände",
        "freilicht",
        "freilichtbühne",
        "freiluft",
        "frischen luft",
        "grunewald",
        "grünen lernort",
        "im freien",
        "open air",
        "open-air",
        "outdoor",
        "park",
        "platz",
        "schloss",
        "straßenfest",
        "tiergarten",
        "umgebung",
        "unterwegs",
        "vor ort",
        "zitadelle",
        "öffentlichkeit",
    ],
    "painting": [
        "aquarell",
        "blatt",
        "farben",
        "farbverläufe",
        "gemaelde",
        "gemalt",
        "gemälde",
        "kunst-workshop",
        "kunstwerke",
        "malen",
        "malerei",
        "painting",
        "tiere",
        "watercolor",
        "ölmalerei",
    ],
    "panel-discussion": ["diskussionsreihe", "gesprächsreihe", "podiumsdiskussion"],
    "parody": ["parodien"],
    "passion": ["passion", "passionsandacht"],
    "percussion": ["schlagzeug", "schlagzeugklasse"],
    "performance": [
        "abschlusskonzert",
        "aufführung",
        "begegnung",
        "dramaturgie",
        "konzert",
        "performance",
        "präsentation",
        "show",
        "theater",
        "vorführung",
        "vorspiel",
    ],
    "performance-art": ["bühnenerlebnis", "exzentrisch"],
    "persian-culture": ["persisch", "persischer"],
    "personal-development": ["persönlichkeitsentwicklung"],
    "personal-narrative": ["lebensgeschichte", "perspektive"],
    "personal-stories": [
        "erfahrungsbericht",
        "erlebnis",
        "erzählungen",
        "perspektive",
        "persönliche geschichten",
    ],
    "personal-story": ["erfahrungen", "lebensgeschichte", "perspektive", "zeugnis"],
    "phil-collins": ["phil collins"],
    "photography": [
        "bilder",
        "bildervortrag",
        "foto",
        "fotografie",
        "photo",
        "photographie",
        "photography",
    ],
    "piano": [
        "klavier",
        "klavierimprovisationen",
        "klavierklasse",
        "pianist",
        "pianistin",
        "piano",
        "tasten",
        "tasteninstrumente",
    ],
    "picture-book-cinema": ["bilderbuchkino"],
    "pilates": ["pilates"],
    "plucked-instruments": ["saiteninstrumente", "zupfinstrumente"],
    "poetry": ["dichtung", "gedicht", "gedichte", "lyrik", "poem", "poesie", "poetry", "rilke"],
    "police": ["mobile wache", "polizei", "polizeibeamtin", "polizeipräsidium", "polizist"],
    "police-recruitment": [
        "berufsberatung",
        "einstellungsverfahren",
        "polizei",
        "polizei einstellung",
        "polizeibeamte",
    ],
    "political-education": [
        "aufklärung",
        "bildungsauftrag",
        "landeszentrale",
        "landeszentrale für politische bildung",
        "politische bildung",
        "politische bildungsarbeit",
        "sensibilisierung",
    ],
    "politics": [
        "antifaschistisch",
        "antifaschistischen widerstand",
        "bamf",
        "demokratische ordnung",
        "ideologie",
        "politik",
        "politisch",
        "politische",
        "politische bildung",
        "politische geschichte",
        "rechtsextremismus",
        "regierung",
        "stadtpolitik",
        "stadtpolitisch",
        "wahlen",
        "widerstand",
    ],
    "pop": ["pop", "popsongs", "schlager"],
    "portuguese": ["portugiesisch", "português"],
    "portuguese-language": ["portugiesisch", "português"],
    "pottery": ["ceramic", "keramik", "keramikkurs", "pottery", "toepfern", "töpfern"],
    "practical-skills": ["alltag anwenden", "anwendbar", "praxisorientiert"],
    "primary-school": ["1. klasse", "2. klasse", "grundschule"],
    "printing": [
        "druck",
        "druckwerkstatt",
        "holzschnitt",
        "linolschnitt",
        "reliefdruck",
        "screen print",
        "siebdruck",
        "textildruck",
    ],
    "privacy": ["datenschutz", "privatsphäre"],
    "professional-development": [
        "berufliche entwicklung",
        "berufliche weiterbildung",
        "fachseminar",
        "kompetenzentwicklung",
    ],
    "psychology": ["emotionale aspekte", "psychologisch"],
    "public-service": ["behörde", "bürgerdienst", "öffentlicher dienst"],
    "punk": ["punk", "punkrock"],
    "puppet-theater": ["figurentheater", "puppentheater", "puppet"],
    "puzzle": ["puzzle", "puzzle-fans", "puzzle-tausch", "puzzles"],
    "pysanka": ["eierverzierung", "pysanka"],
    "queen": ["freddie mercury", "queen"],
    "queen-tribute": ["queen", "tribute"],
    "queer": ["lesbisch", "lgbtq", "pride", "queer", "queeres", "schwul", "trans"],
    "quiz": ["quiz", "quiznachmittag", "quiznight"],
    "racism": ["rassismus", "rassistischer anschlag"],
    "rap": ["rap"],
    "ravel": ["ravel"],
    "reading": [
        "austausch",
        "austausch über bücher",
        "besprechen",
        "besprechung",
        "buchauswahl",
        "buchbesprechung",
        "buchclub",
        "buchklub",
        "bücher",
        "deutsch",
        "leseerlebnis",
        "lesefähigkeiten",
        "leseförderung",
        "leseklub",
        "lesekreis",
        "lesenlernen",
        "lesung",
        "literaturclub",
        "reading",
        "roda de leitura",
        "vorlesen",
        "vorlesestunde",
        "vorlesung",
    ],
    "reading-group": ["buchclub", "lesekreis"],
    "recreation": [
        "entspannung",
        "freizeit",
        "freizeitaktivität",
        "freizeitbeschäftigung",
        "freizeitgestaltung",
        "hobby",
        "unterhaltung",
    ],
    "recruitment": ["ausbildung", "bewerbung", "einstellung", "einstellungsverfahren"],
    "recurring": [
        "dienstag",
        "every wednesday",
        "jeden 1. mittwoch",
        "jeden 1. mittwoch im monat",
        "jeden dienstag",
        "jeden mittwoch",
        "jeden zweiten freitag im monat",
        "mittwoch",
        "monatlich",
        "regelmäßig",
        "wöchentlich",
    ],
    "reggae": ["reggae"],
    "regular-class": ["regelmäßig", "wöchentlich"],
    "regular-event": [
        "jeden 1. mittwoch",
        "jeden 1. mittwoch im monat",
        "jeden monat",
        "regelmäßig",
    ],
    "religion": [
        "andacht",
        "glaube",
        "glauben",
        "judentum",
        "passionsandacht",
        "religion",
        "religionen",
        "religiös",
        "synagoge",
        "ökumenisch",
        "ökumenische",
    ],
    "religious": ["andacht", "religiös", "ökumenisch"],
    "religious-music": ["geistlich", "marienlieder", "stabat mater"],
    "repair": ["reparieren"],
    "repair-cafe": [
        "repair cafe",
        "repair café",
        "repair-café",
        "reparatur",
        "reparaturbildung",
        "reparaturwerkstatt",
        "reparieren",
        "selbst reparieren",
        "selbstreparatur",
    ],
    "research": ["archive", "recherche"],
    "research-methods": ["recherche", "recherchemethoden"],
    "resistance": [
        "antifaschistisch",
        "antifaschistischer widerstand",
        "widerstand",
        "widerstandskampf",
    ],
    "right-wing-extremism": [
        "nsu",
        "rechter terror",
        "rechtsextremismus",
        "rechtsterrorismus",
        "rechtsterroristisch",
    ],
    "robotics": ["robot", "robotics", "robotik"],
    "rock": ["rock", "rock'n'roll", "rockband", "rockmusik"],
    "rock-and-roll": ["rock and roll", "rock'n'roll"],
    "rock-pop": ["80er", "klassiker", "ndw", "neue deutsche welle"],
    "role-playing": [
        "d&d",
        "dungeons & dragons",
        "pen & paper",
        "pen and paper",
        "rollenspiel",
        "spiel",
        "spiele",
        "spieltermine",
        "spielzeit",
        "tabletop",
    ],
    "rolling-stones": ["rolling stones"],
    "running": ["cross-lauf", "joggen", "jogging", "lauf", "laufen", "marathon", "running"],
    "sacred-music": ["geistliche musik", "marienlieder", "stabat mater"],
    "safety": ["prävention", "sicher", "sicherheit", "unfallverhütung", "verkehrssicherheit"],
    "salsa": ["salsa"],
    "samba": ["samba"],
    "satire": ["satire", "satirisch"],
    "schlager": ["schlager", "schlagersterne", "schlagerstunde"],
    "school": ["berufliche schulen", "grundschule", "klassen", "schule", "schulwettkampf"],
    "school-competition": ["ausscheid", "schulen", "weiterführende schulen"],
    "school-event": ["schule", "schulhockey"],
    "school-groups": ["grundschulen", "kitas", "schulen", "schulklassen"],
    "school-holidays": ["osterferien"],
    "school-program": ["schule", "sekundarschule"],
    "schubert": ["schubert"],
    "schönberg": ["schönberg"],
    "science": [
        "bodenexpertin",
        "bodenexpertise",
        "experimente",
        "experimentieren",
        "forschen",
        "forschung",
        "research",
        "science",
        "wissenschaft",
    ],
    "sculpture": ["bildhauerei", "plastik", "sculpture", "skulptur"],
    "self-confidence": ["selbstbewusstsein", "selbstwertgefühl"],
    "self-defense": ["eigenschutz", "körperliche kompetenzen"],
    "self-help": [
        "alltag",
        "eigenständige entscheidungsfindung",
        "innere balance",
        "leichtigkeit",
        "motivation",
        "persönliche entwicklung",
        "persönliche weise",
        "persönlichkeitsentwicklung",
        "seele",
        "seelisches gleichgewicht",
        "selbstbewusstsein",
        "selbsthilfe",
        "selbsthilfegruppe",
        "selbstwertgefühl",
        "self-help",
        "sorgen",
        "wohlbefinden",
        "ängste",
    ],
    "senior": ["alter", "senioren", "seniorinnen"],
    "senior-friendly": [
        "55+",
        "60 jahre",
        "alter",
        "digital-lots:innen",
        "digital-lotsen",
        "digitale formulare",
        "digitale lotsen",
        "für senioren",
        "generation 55+",
        "generation plus",
        "kaffeegedeck",
        "nachmittag",
        "neuköllner bibliotheken",
        "senioren",
        "tanznachmittag",
        "älter werdende menschen",
        "ältere menschen",
        "ü-55",
    ],
    "sensory-experience": [
        "ertasten",
        "riechen",
        "schmecken",
        "sehen, hören, riechen, schmecken, ertasten",
        "sensorisch",
        "sinne",
        "sinneserfahrung",
        "sinneserlebnis",
    ],
    "sensory-learning": ["fühlen", "riechen", "schmecken", "sinne"],
    "sewing": ["naehen", "nähen", "nähprojekt", "nähtreff", "nähwerkstatt", "schneidern", "sewing"],
    "singer-songwriter": [
        "clara werden",
        "deutsche lieder",
        "interpret",
        "künstler",
        "liedermacher",
        "musik",
        "musikalisches programm",
        "sinatra interpret",
        "singer-songwriter",
        "solo-künstler",
        "sänger",
        "sängerin",
    ],
    "singing": [
        "gesangs-improvisation",
        "heilsames singen",
        "lieder",
        "mitsingen",
        "singen",
        "singerfahrung",
        "singleitung",
        "singworkshop",
        "vocalcoach",
    ],
    "ska": ["ska"],
    "skill-building": ["fertigkeiten", "kompetenzen"],
    "small-group": ["kleine gruppe", "kleine gruppen", "maximal 8 teilnehmern"],
    "small-groups": ["individuelle betreuung", "kleine gruppen"],
    "smartphone": ["handy", "internet", "mobil", "mobile", "mobiltelefon", "smartphone"],
    "social": [
        "freunde",
        "gemeinsam",
        "gemeinschaft",
        "gespräche",
        "nachmittag",
        "show",
        "sozial",
        "treffen",
        "treffpunkt",
        "veranstaltung",
        "zusammen",
        "zusammenkommen",
    ],
    "social-activism": ["aktivismus", "politische bildung"],
    "social-craft": ["kreative nachmittage"],
    "social-dance": ["alleinunterhalter", "geselliger tanz", "geselligkeit", "tanznachmittag"],
    "social-dancing": [
        "alleinunterhalter",
        "gemeinsames tanzen",
        "geselligkeit",
        "nachmittag",
        "tanzcafé",
        "tanzveranstaltung",
    ],
    "social-gathering": ["gespräch", "gespräche", "plaudern", "treffen", "zusammenkommen"],
    "social-history": [
        "familiäres erinnern",
        "gesellschaftsgeschichte",
        "gesellschafts­geschichte",
        "kollektives erinnern",
    ],
    "social-inequality": ["armut", "soziale ungleichheit"],
    "social-issues": [
        "armut",
        "konflikte",
        "menschenrecht",
        "politische bildung",
        "soziale themen",
        "wohnungslosigkeit",
        "wohnungsmarkt",
    ],
    "social-justice": [
        "anerkennung",
        "armut",
        "diskriminierungskritische bildung",
        "gerechtigkeit",
        "gesellschaftliche perspektive",
        "gesellschaftliche perspektiven",
        "gewalt",
        "gleichbehandlung",
        "grundbedürfnisse",
        "menschenrechte",
        "obdachlosigkeit",
        "perspektive",
        "politische bildung",
        "recht auf wohnen",
        "rechte",
        "social justice",
        "soziale gerechtigkeit",
        "teilhabe",
        "wohnungslose",
    ],
    "social-policy": [
        "menschenrecht",
        "menschenrechte",
        "politik",
        "politische bildung",
        "regulierung",
        "sozialpolitik",
        "stadtpolitik",
        "wohnungslosigkeit",
        "wohnungsmarkt",
        "wohnungspolitik",
    ],
    "social-services": ["sozialassistenz", "sozialwesen"],
    "social-skills": ["kontaktfähigkeit", "soziale fähigkeiten"],
    "social-work": ["sozialpädagogik", "sozialwesen"],
    "society": ["arbeitswelt", "gesellschaft", "gesellschaftskritik"],
    "soil-ecology": ["boden", "bodenbildung", "bodennetzwerk", "mikroorganismen"],
    "solidarity": ["solidarität"],
    "soul": ["soul"],
    "south-america": ["chile", "südamerika"],
    "spirituality": ["andacht", "geistlich"],
    "sports": ["amateur:innensport", "crosslauf", "sport", "sportvereine", "turnier"],
    "sports-tournament": ["pokal", "turnier"],
    "spring": ["frühling", "frühlingsboten"],
    "spring-concert": ["frühlingskonzert"],
    "stem": ["naturwissenschaften", "naturwissenschaftlich", "stem"],
    "stock-market": ["wertpapiere"],
    "stocks": ["aktien"],
    "storytelling": [
        "bilderbücher",
        "erfahrungsberichte",
        "erinnerung",
        "erlebnis",
        "erzaehlung",
        "erzählen",
        "erzählung",
        "erzählungen",
        "geschichten",
        "geschichtserzählung",
        "kino für die ohren",
        "legendendbildungen",
        "lieder aus dem leben",
        "narration",
        "narrative",
        "persönliche geschichten",
        "plaudern",
        "storytelling",
        "texte",
        "traditionsbildung",
        "vorlesen",
        "vorlesestunde",
        "vortrag",
        "wassermann",
    ],
    "strategy": ["strategisches denken", "taktisches denken"],
    "street-art": ["graffiti", "mural", "street art", "streetart", "urban art"],
    "strength-training": ["kraft", "krafttraining"],
    "string-instruments": ["streicher", "streichinstrumente"],
    "strings": ["streicher", "streichhölzer", "streichinstrumente"],
    "student-performance": [
        "klassenabend",
        "schulkonzert",
        "schüler",
        "schüler:innenvorspiel",
        "schülerauftritt",
        "schülerinnen",
        "schülerinnen und schüler",
        "schülerkonzert",
        "schülervorspiel",
        "vorspiel",
    ],
    "student-recital": ["schüler:innenvorspiel", "schülervorspiel", "vorspiel"],
    "students": ["jugendlichen", "schulunterricht", "schüler", "schüler:innen"],
    "study-support": ["abitur", "lernhilfe", "msa", "prüfungshilfe"],
    "summer": ["sommer"],
    "summer-concert": ["sommerkonzert"],
    "support": ["unterstützung"],
    "support-service": ["unterstützung"],
    "sustainability": [
        "bio-landwirtschaft",
        "bioregionale wertschöpfung",
        "lieferketten",
        "nachhaltig",
        "nachhaltige entwicklung",
        "solidarisch",
        "zukunft",
    ],
    "swap-meet": [
        "börse",
        "swap",
        "tausch",
        "tausch-börse",
        "tauschbörse",
        "tauschen",
        "tauschmarkt",
    ],
    "swimming": ["schwimmen", "schwimmwettkampf", "swimming"],
    "swing": ["swing"],
    "table-tennis": ["ping pong", "pingpong", "table tennis", "tischtennis"],
    "tablet": ["digitale geräte", "tablet"],
    "tango": ["tango"],
    "teacher-training": [
        "erzieherausbildung",
        "erzieherin",
        "fortbildung",
        "kollegium",
        "lehrerfortbildung",
        "lehrkräfte",
        "pädagogisch",
    ],
    "teachers": ["lehrkräfte", "pädagogische fachkräfte"],
    "teaching": ["didaktisch", "pädagogik"],
    "teaching-methods": ["bildungspraxis", "formate", "methoden"],
    "teaching-resources": ["bildungsmaterialien", "unterrichtsmaterialien"],
    "tech-support": ["problem", "problemlösung", "technische hilfe", "unterstützung"],
    "techno": ["techno"],
    "technology": [
        "android",
        "apps",
        "digital",
        "digital-lot:innen",
        "digitale angebote",
        "digitale formularen",
        "digitale kompetenzen",
        "digitale technologie",
        "digitalen",
        "digitalisierung",
        "e-reader",
        "geräte",
        "handy",
        "internet",
        "ki",
        "künstliche intelligenz",
        "online-katalog",
        "selbstverbuchungsautomaten",
        "smartphone",
        "tech",
        "technik",
        "technisch",
        "technologie",
        "technology",
    ],
    "technology-support": ["techniksprechstunde"],
    "teen-friendly": ["ab 13 jahren", "jugendliche"],
    "teens": ["jugendliche", "schüler"],
    "terrorism": ["terror", "terrorismus"],
    "test-preparation": ["abitur", "msa", "prüfungen"],
    "textile-arts": ["textildruck"],
    "textile-design": ["textildesign", "textildruck"],
    "textile-printing": [
        "bedrucken",
        "kleidung bedrucken",
        "textilbedrucken",
        "textilbedruckung",
        "textildruck",
        "textilien bedrucken",
        "textilpresse",
    ],
    "theater": [
        "kindertheater",
        "musikalisches theater",
        "musiktheater",
        "stück",
        "theater",
        "theaterabend",
        "theatral",
        "vorstellung",
    ],
    "tina-turner": ["tina turner"],
    "tolerance": ["akzeptanz", "respektvoll", "toleranz"],
    "tournament": ["challenge", "turnier"],
    "traditional-crafts": ["traditionelle handwerkskunst", "traditionelle techniken"],
    "traffic": ["straßenverkehr", "verkehr"],
    "traffic-education": ["straßenverkehr", "verkehrserziehung"],
    "traffic-safety": ["straßenverkehr", "verkehrssicherheit", "verkehrssicherheitsberatung"],
    "trauma": ["trauma"],
    "travel": ["konstanz", "orte der welt", "reise", "reisen", "reiseroute"],
    "travel-writing": ["reiseerfahrungen", "reisen"],
    "tribute": ["programm", "tribut"],
    "tribute-band": [
        "beatles-tribute",
        "coverband",
        "queen-tribute",
        "tribut",
        "tribute",
        "tribute band",
        "tribute-band",
        "tributeband",
        "ärzte tribute",
    ],
    "trivia": ["allgemeinwissen", "pubquiz", "quiz", "quiznight", "wissensquiz"],
    "troubleshooting": [
        "einstellungen",
        "fehlersuche",
        "probleme",
        "problemlösung",
        "unterstützung",
    ],
    "tutoring": [
        "förderunterricht",
        "lerntandem",
        "lernunterstützung",
        "nachhilfe",
        "prüfungshilfe",
        "unterstützung",
    ],
    "ukrainian-culture": ["ukrainisch", "ukrainische kultur"],
    "ukulele": ["ukulele", "ukulele-spielkreis", "ukulelenklasse", "ukulelenkurs"],
    "upcycling": [
        "aufkleber-design",
        "basteln",
        "collage",
        "collagen",
        "diy",
        "kleidung reparieren",
        "kleidung verschönern",
        "kreativ gestalten",
        "kreative materialien",
        "lieblingsteile verschönern",
        "materialien",
        "nachhaltig",
        "nachhaltiges design",
        "recycelt",
        "recycling",
        "spenden",
        "stoffe",
        "stoffe aus spenden",
        "stoffreste",
        "techniken",
        "umgestaltung",
        "upcycling",
        "verschiedene materialien",
    ],
    "urban-development": ["stadtentwicklung"],
    "urban-history": ["stadtentwicklung", "stadtgeschichte"],
    "urban-planning": ["stadt", "stadtentwicklung", "stadtpolitik", "stadtraum", "wohnungsbau"],
    "urban-policy": ["politik", "stadtpolitik"],
    "urban-space": ["stadtraum", "öffentlicher raum"],
    "vegan": ["vegan"],
    "vegetarian": ["vegetarian", "vegetarisch"],
    "venice": ["serenissima", "venedig"],
    "vhs": ["vhs", "volkshochschule"],
    "video-art": ["media art", "medienkunst", "video art", "videokunst"],
    "viola": ["bratsche", "viola"],
    "violin": ["geige", "violin", "violine"],
    "vocal": [
        "bassbariton",
        "gesangsklasse",
        "stimmbildung",
        "stimme",
        "sängerin",
        "vier oktaven",
        "vorspiel",
    ],
    "vocal-coaching": ["vocalcoach", "vocalcoaching"],
    "vocal-improvisation": ["gesangs-improvisation", "improvisation"],
    "vocal-wellness": ["gesundheitserreger", "heilsames singen"],
    "vocational-training": [
        "ausbildung",
        "auszubildende",
        "beruf",
        "berufliche orientierung",
        "berufsausbildung",
        "berufsvorbereitlung",
        "berufsvorbereitung",
    ],
    "volleyball": ["volleyball"],
    "walking-tour": ["führung", "rundgang", "stadtführung", "stadtrundgang"],
    "weekly": ["jeden donnerstag", "wöchentlich"],
    "weekly-event": ["jeden donnerstag", "regelmäßig"],
    "weimar-cinema": ["1932", "stumm- und tonfilme", "weimar"],
    "wellbeing": ["gesundheit", "wohlbefinden"],
    "wind-instruments": ["blasinstrumente", "bläser"],
    "wine": ["wein", "weinprobe", "wine"],
    "women's-issues": ["frau", "frauen"],
    "women-empowerment": ["frau", "frauen"],
    "women-ensemble": ["frauenchor", "frauenensemble"],
    "woodwork": ["holzarbeit", "holzbearbeitung", "holzwerkstatt", "tischlerei", "woodwork"],
    "woodworking": ["linealanschlag", "werkstatt"],
    "workshop": [
        "ausprobieren",
        "gestalten",
        "kreativ",
        "kreativ gestalten",
        "modul",
        "praxiserprobung",
        "selbst gestalten",
        "workshop",
        "zum ausprobieren",
    ],
    "world-folk": [
        "brasil",
        "brasilianische musik",
        "brasilien",
        "chile",
        "deutschland",
        "frankreich",
        "musik aus aller welt",
        "usa",
    ],
    "world-music": [
        "chants aus aller welt",
        "indische mantren",
        "musik aus aller welt",
        "weltmusik",
        "world music",
    ],
    "writing": ["schreibcafé", "schreiben", "schreibwerkstatt"],
    "wwii": [
        "1920er jahre",
        "1933",
        "1933-1945",
        "1944",
        "antifaschismus",
        "antifaschistisch",
        "antifaschistischer widerstand",
        "faschismus",
        "holocaust",
        "nationalsozialismus",
        "nationalsozialisten",
        "nazi",
        "nazi-widerstand",
        "nazi-zeit",
        "nazijäger",
        "ns-zeit",
        "weltkrieg",
        "widerstand",
        "zwangsarbeit",
        "zweiter weltkrieg",
        "zwischenkriegszeit",
    ],
    "yoga": ["yoga"],
    "yoga-fitness": ["bewegung", "fitness", "körper", "training", "wohlbefinden"],
    "youth": [
        "13 bis 15 jahren",
        "grundschulen",
        "jugend",
        "jugendliche",
        "jugendlichen",
        "junge menschen",
        "kinder",
        "kinder- und jugendchor",
        "mini-pokal",
        "oberschulen",
        "schulhockey",
        "schüler",
        "schüler:innen",
        "schülerinnen",
        "sek ii",
        "u14",
        "weiterführende schulen",
    ],
    "youth-ensemble": ["ensemble", "jugendorchester"],
    "youth-literature": ["ab 14 jahren", "jugendsachbuch"],
    "youth-music": ["jugend musiziert", "nachwuchswettbewerb"],
    "youth-sports": ["jtfo", "jugend", "jugend trainiert für olympia", "jugendliche", "u16"],
}

# ── Pre-compiled patterns ───────────────────────────────────────────────────

_COMPILED_SUB_PATTERNS: dict[str, dict[str, re.Pattern]] = {}
_COMPILED_TAG_PATTERNS: dict[str, re.Pattern] = {}


def _get_sub_patterns() -> dict[str, dict[str, re.Pattern]]:
    """Lazily compile subcategory keyword patterns."""
    if _COMPILED_SUB_PATTERNS:
        return _COMPILED_SUB_PATTERNS
    for category, subs in SUBCATEGORY_KEYWORDS.items():
        _COMPILED_SUB_PATTERNS[category] = {}
        for subcategory, keywords in subs.items():
            escaped = [re.escape(k) for k in keywords]
            pattern = re.compile(
                r"(?:^|[\s\-,;:.(!/])(?:" + "|".join(escaped) + r")(?:[\s\-,;:.)!/]|$)",
                re.IGNORECASE,
            )
            _COMPILED_SUB_PATTERNS[category][subcategory] = pattern
    return _COMPILED_SUB_PATTERNS


def _get_tag_patterns() -> dict[str, re.Pattern]:
    """Lazily compile tag keyword patterns."""
    if _COMPILED_TAG_PATTERNS:
        return _COMPILED_TAG_PATTERNS
    for tag, keywords in TAG_KEYWORDS.items():
        escaped = [re.escape(k) for k in keywords]
        pattern = re.compile(
            r"(?:^|[\s\-,;:.(!/])(?:" + "|".join(escaped) + r")(?:[\s\-,;:.)!/]|$)",
            re.IGNORECASE,
        )
        _COMPILED_TAG_PATTERNS[tag] = pattern
    return _COMPILED_TAG_PATTERNS


def classify_event(
    title: str,
    description: str | None,
    category: str | None = None,
    existing_tags: list[str] | None = None,
) -> dict[str, str | list[str] | None]:
    """
    Classify an event into category/subcategory and extract English keyword tags.

    Args:
        title: Event title
        description: Event description (optional)
        category: Pre-assigned category (e.g. from source_tag mapping)
        existing_tags: Tags already on the event (from scraper)

    Returns:
        dict with keys: category, subcategory, keyword_tags (English tags found)
    """
    text = f"{title} {description or ''}"
    tag_text = " ".join(existing_tags or [])
    search_text = f"{text} {tag_text}"

    # 1. Determine subcategory from keywords
    sub_patterns = _get_sub_patterns()
    categories_to_check = (
        [category] if category and category in sub_patterns else list(sub_patterns.keys())
    )

    best_subcategory: str | None = None

    for cat in categories_to_check:
        if cat not in sub_patterns:
            continue
        for subcategory, pattern in sub_patterns[cat].items():
            if pattern.search(search_text):
                if not best_subcategory:
                    best_subcategory = subcategory
                    if not category:
                        category = cat
                break  # first match wins within category

    # 2. Extract English tags from keywords
    tag_patterns = _get_tag_patterns()
    found_tags: list[str] = []

    for tag, pattern in tag_patterns.items():
        if pattern.search(search_text):
            if tag not in found_tags:
                found_tags.append(tag)

    return {
        "category": category,
        "subcategory": best_subcategory,
        "keyword_tags": found_tags,
    }
